name:                Ch25
version:             0.1.0.0
github:              "Neo03/Ch25"
license:             BSD3
author:              "Vasiliy Simakov"
maintainer:          "vasimakov87@gmail.com"
copyright:           "2018 Vasiliy Simakov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Neo03/Ch25#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Ch25-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Ch25

tests:
  Ch25-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Ch25
